// Code generated by protoc-gen-go. DO NOT EDIT.
// source: NameNode.proto

package lab2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chunk struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_e56228e413a39553, []int{0}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_e56228e413a39553, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Proposal struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Chunk                *Chunk   `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_e56228e413a39553, []int{2}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Proposal) GetChunk() *Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func init() {
	proto.RegisterType((*Chunk)(nil), "lab2.Chunk")
	proto.RegisterType((*Message)(nil), "lab2.Message")
	proto.RegisterType((*Proposal)(nil), "lab2.Proposal")
}

func init() {
	proto.RegisterFile("NameNode.proto", fileDescriptor_e56228e413a39553)
}

var fileDescriptor_e56228e413a39553 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xf3, 0x4b, 0xcc, 0x4d,
	0xf5, 0xcb, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x49, 0x4c, 0x32,
	0x52, 0xd2, 0xe7, 0x62, 0x75, 0xce, 0x28, 0xcd, 0xcb, 0x16, 0x12, 0xe2, 0x62, 0xc9, 0x03, 0x2a,
	0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x29, 0x89, 0x25, 0x89, 0x12,
	0x4c, 0x40, 0x31, 0x9e, 0x20, 0x30, 0x5b, 0x49, 0x96, 0x8b, 0xdd, 0x37, 0xb5, 0xb8, 0x38, 0x31,
	0x1d, 0x2c, 0x5d, 0x92, 0x5a, 0x51, 0x02, 0xd3, 0x02, 0x62, 0x2b, 0xd9, 0x72, 0x71, 0x04, 0x14,
	0xe5, 0x17, 0xe4, 0x17, 0x27, 0xe6, 0x08, 0xf1, 0x71, 0x31, 0x65, 0x16, 0x40, 0x65, 0x81, 0x2c,
	0x21, 0x45, 0x2e, 0xd6, 0x64, 0x90, 0x5d, 0x60, 0xf3, 0xb8, 0x8d, 0xb8, 0xf5, 0x40, 0x2e, 0xd0,
	0x03, 0x5b, 0x1f, 0x04, 0x91, 0x31, 0x5a, 0xc9, 0xc8, 0xc5, 0x01, 0x73, 0xa7, 0x90, 0x2e, 0x17,
	0x47, 0x78, 0x51, 0x66, 0x49, 0xaa, 0x4f, 0x7e, 0xba, 0x10, 0x1f, 0x44, 0x31, 0xcc, 0x6c, 0x29,
	0x5e, 0x08, 0x1f, 0xea, 0x14, 0x25, 0x06, 0x0d, 0x46, 0x21, 0x13, 0x2e, 0x9e, 0xe0, 0xd4, 0xbc,
	0x14, 0x84, 0xf5, 0x68, 0x5a, 0xd0, 0xf8, 0x20, 0x3d, 0x06, 0x8c, 0x42, 0x16, 0x5c, 0x02, 0xee,
	0xa9, 0x79, 0xa9, 0x45, 0x89, 0x25, 0xa9, 0xa4, 0xe9, 0x4c, 0x62, 0x03, 0x87, 0xa3, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0xb8, 0xc1, 0x42, 0x59, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NameNodeClient is the client API for NameNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NameNodeClient interface {
	WriteLog(ctx context.Context, opts ...grpc.CallOption) (NameNode_WriteLogClient, error)
	//Centralizado
	SendProposal(ctx context.Context, opts ...grpc.CallOption) (NameNode_SendProposalClient, error)
	GenerateProposal(ctx context.Context, opts ...grpc.CallOption) (NameNode_GenerateProposalClient, error)
}

type nameNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNameNodeClient(cc grpc.ClientConnInterface) NameNodeClient {
	return &nameNodeClient{cc}
}

func (c *nameNodeClient) WriteLog(ctx context.Context, opts ...grpc.CallOption) (NameNode_WriteLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NameNode_serviceDesc.Streams[0], "/lab2.NameNode/WriteLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &nameNodeWriteLogClient{stream}
	return x, nil
}

type NameNode_WriteLogClient interface {
	Send(*Proposal) error
	CloseAndRecv() (*Message, error)
	grpc.ClientStream
}

type nameNodeWriteLogClient struct {
	grpc.ClientStream
}

func (x *nameNodeWriteLogClient) Send(m *Proposal) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nameNodeWriteLogClient) CloseAndRecv() (*Message, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nameNodeClient) SendProposal(ctx context.Context, opts ...grpc.CallOption) (NameNode_SendProposalClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NameNode_serviceDesc.Streams[1], "/lab2.NameNode/SendProposal", opts...)
	if err != nil {
		return nil, err
	}
	x := &nameNodeSendProposalClient{stream}
	return x, nil
}

type NameNode_SendProposalClient interface {
	Send(*Proposal) error
	Recv() (*Proposal, error)
	grpc.ClientStream
}

type nameNodeSendProposalClient struct {
	grpc.ClientStream
}

func (x *nameNodeSendProposalClient) Send(m *Proposal) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nameNodeSendProposalClient) Recv() (*Proposal, error) {
	m := new(Proposal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nameNodeClient) GenerateProposal(ctx context.Context, opts ...grpc.CallOption) (NameNode_GenerateProposalClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NameNode_serviceDesc.Streams[2], "/lab2.NameNode/GenerateProposal", opts...)
	if err != nil {
		return nil, err
	}
	x := &nameNodeGenerateProposalClient{stream}
	return x, nil
}

type NameNode_GenerateProposalClient interface {
	Send(*Proposal) error
	Recv() (*Proposal, error)
	grpc.ClientStream
}

type nameNodeGenerateProposalClient struct {
	grpc.ClientStream
}

func (x *nameNodeGenerateProposalClient) Send(m *Proposal) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nameNodeGenerateProposalClient) Recv() (*Proposal, error) {
	m := new(Proposal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NameNodeServer is the server API for NameNode service.
type NameNodeServer interface {
	WriteLog(NameNode_WriteLogServer) error
	//Centralizado
	SendProposal(NameNode_SendProposalServer) error
	GenerateProposal(NameNode_GenerateProposalServer) error
}

// UnimplementedNameNodeServer can be embedded to have forward compatible implementations.
type UnimplementedNameNodeServer struct {
}

func (*UnimplementedNameNodeServer) WriteLog(srv NameNode_WriteLogServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteLog not implemented")
}
func (*UnimplementedNameNodeServer) SendProposal(srv NameNode_SendProposalServer) error {
	return status.Errorf(codes.Unimplemented, "method SendProposal not implemented")
}
func (*UnimplementedNameNodeServer) GenerateProposal(srv NameNode_GenerateProposalServer) error {
	return status.Errorf(codes.Unimplemented, "method GenerateProposal not implemented")
}

func RegisterNameNodeServer(s *grpc.Server, srv NameNodeServer) {
	s.RegisterService(&_NameNode_serviceDesc, srv)
}

func _NameNode_WriteLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NameNodeServer).WriteLog(&nameNodeWriteLogServer{stream})
}

type NameNode_WriteLogServer interface {
	SendAndClose(*Message) error
	Recv() (*Proposal, error)
	grpc.ServerStream
}

type nameNodeWriteLogServer struct {
	grpc.ServerStream
}

func (x *nameNodeWriteLogServer) SendAndClose(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nameNodeWriteLogServer) Recv() (*Proposal, error) {
	m := new(Proposal)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NameNode_SendProposal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NameNodeServer).SendProposal(&nameNodeSendProposalServer{stream})
}

type NameNode_SendProposalServer interface {
	Send(*Proposal) error
	Recv() (*Proposal, error)
	grpc.ServerStream
}

type nameNodeSendProposalServer struct {
	grpc.ServerStream
}

func (x *nameNodeSendProposalServer) Send(m *Proposal) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nameNodeSendProposalServer) Recv() (*Proposal, error) {
	m := new(Proposal)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NameNode_GenerateProposal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NameNodeServer).GenerateProposal(&nameNodeGenerateProposalServer{stream})
}

type NameNode_GenerateProposalServer interface {
	Send(*Proposal) error
	Recv() (*Proposal, error)
	grpc.ServerStream
}

type nameNodeGenerateProposalServer struct {
	grpc.ServerStream
}

func (x *nameNodeGenerateProposalServer) Send(m *Proposal) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nameNodeGenerateProposalServer) Recv() (*Proposal, error) {
	m := new(Proposal)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NameNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lab2.NameNode",
	HandlerType: (*NameNodeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteLog",
			Handler:       _NameNode_WriteLog_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendProposal",
			Handler:       _NameNode_SendProposal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GenerateProposal",
			Handler:       _NameNode_GenerateProposal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "NameNode.proto",
}
